FROM python:3.11-slim

WORKDIR /app

# Install dependencies
RUN pip install flask prometheus_client numpy joblib scikit-learn

# Copy model and exporter files
COPY 3.prometheus_exporter.py app.py
COPY model.pkl model.pkl
COPY feature_names.json feature_names.json
COPY model_info.json model_info.json

EXPOSE 8000

CMD ["python", "app.py"]
